# Nae of workflow
name: My test workflow

# Define the trigger event(s)
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs:   
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello, Github Actions!"
            
    # Job to build and test. By writing needs, this job will
    # not be run before the required job has completed. Otherwise it will run 
    # in parallel.
    build-and-test:
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:
          # Use github.com/actions/checkout to check out this repo
          - name: Checkout this repo
            uses: actions/checkout@v3
          - name: Install dependencies
            run: sudo apt install -y build-essential python3
          # See where we are in the VM 
          - run: pwd 

          - name: Run tests
            run: python3 test.py
